### ISSUE TITLE
Can't create a table for model

### ISSUE THREAD

**Issue by nibarulabs** [gitblit/iciql#36]
I'm using H2 embedded db and keep getting this error

``Exception in thread "main" com.iciql.IciqlException: Table "MY_TEST" not found; SQL statement:``

when I try to fetch anything from the my_test table.

For my model, I have this:

```
@Iciql.IQTable(name = "my_test")
@Iciql.IQIndexes({
        @Iciql.IQIndex(name="exchange", value="exchange")
})
@Iciql.IQVersion(value = 1)

public class MyTest {

    @Iciql.IQColumn(name = "id", primaryKey = true, autoIncrement = true)
    public Long        id;

    @Iciql.IQColumn(name = "exchange", length = 20, trim = true)
    public String      exchange;
}
```

My database helper class init code looks like so:

```
Class.forName("org.h2.Driver");
JdbcDataSource jdbcDataSource = new JdbcDataSource();
jdbcDataSource.setURL(dbConnectionString);
jdbcDataSource.setUser(DbUsername);
jdbcDataSource.setPassword(DbPassword);

this.db = Db.open(jdbcDataSource, Iciql.Mode.PROD);
DatabaseUpgrader upgrader = new DatabaseUpgrader();
db.setDbUpgrader(upgrader);
```

this.db is for a ```private Db db;``` instance var I have for the database helper class. My upgrader doesn't do anything right now except print out messages on when it is being called - nothing is printing out and not setting the upgrader doesn't do anything.

Here's the full stack trace:

Connection string for the db (the file gets created and I can connect to it via the h2 tools) looks like:

```
jdbc:h2:file:/Users/test/my-test-project/run/data/my-test
```

I read through a lot of the iciql code trying to figure out where the table get's automatically created. I've also read through the tests to try to adjust my code to resemble working test code. Still, no luck.

The project is confidential, so I can't include any of it here, unfortunately. But the above is fairly close. I'm pretty much blocked at this point 

Here's the full stack trace:

```
Exception in thread "main" com.iciql.IciqlException: Table "MY_TEST" not found; SQL statement:
select * from my_test where exchange = ? [42102-197]
	at com.iciql.Db.executeQuery(Db.java:796)
	at com.iciql.DaoProxy.executeQuery(DaoProxy.java:190)
	at com.iciql.DaoProxy.invoke(DaoProxy.java:117)
	at com.sun.proxy.$Proxy39.findExchange(Unknown Source)
	at com.my-test.services.ExchangeCacheService.fetchDataFromDatabase(ExchangeCacheService.java:180)
	at com.my-test.services.ExchangeCacheService.getExchangeData(ExchangeCacheService.java:51)
	at com.my-test.Application.main(Application.java:50)
Caused by: org.h2.jdbc.JdbcSQLException: Table "MY_TEST" not found; SQL statement:
select * from my_test where exchange = ? [42102-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.Parser.readTableOrView(Parser.java:5920)
	at org.h2.command.Parser.readTableFilter(Parser.java:1430)
	at org.h2.command.Parser.parseSelectSimpleFromPart(Parser.java:2138)
	at org.h2.command.Parser.parseSelectSimple(Parser.java:2287)
	at org.h2.command.Parser.parseSelectSub(Parser.java:2133)
	at org.h2.command.Parser.parseSelectUnion(Parser.java:1946)
	at org.h2.command.Parser.parseSelect(Parser.java:1919)
	at org.h2.command.Parser.parsePrepared(Parser.java:463)
	at org.h2.command.Parser.parse(Parser.java:335)
	at org.h2.command.Parser.parse(Parser.java:307)
	at org.h2.command.Parser.prepareCommand(Parser.java:278)
	at org.h2.engine.Session.prepareLocal(Session.java:611)
	at org.h2.engine.Session.prepareCommand(Session.java:549)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1247)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:76)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:304)
	at com.iciql.Db.executeQuery(Db.java:786)
```

Thanks.

**Comment by nibarulabs** [comment]
I figured out why this is happening.

I am running a select _first_ on the table. In the code (haven't pinned down exactly where) the table is only created on an INSERT being called.

My expected behavior is that iciql would check for the table(s) on startup and create them.

I'm using H2 and when I insert 1 record, the table gets created and everything works fine. However, that row is mostly null and this is really a hack.

Currently my code queries the my_test table first and if it's empty, inserts the data. I guess I will have to re-work my code to check if the table exists and if not, then proceed with the insert, bypassing the query.

Good to know, closing.
